### PR TITLE
feat: Add OpenSearch support

### PR DESCRIPTION
**Pull request by BYK**
https://developer.mozilla.org/en-US/docs/Web/OpenSearch

### CODE REVIEW

**Comment by BYK** [comment]
Ping?

**Comment by itsojon** [comment]
Thank you for the PR, @BYK, and apologies for the slow slow reply! This looks great. I'll take a closer look at it in the near future and let you know if I have any feedback before merging.

**Comment by BYK** [comment]
@itsojon ping? :D

**Review by itsojon — APPROVED** [review]
@BYK so so sorry for the continued wait, and thank you again for the PR! you can count on future PRs being reviewed much, much faster.

**Pull request merged**
